#!/usr/bin/env node

var decrypt = require('./crypto_helper').decrypt

if (process.argv.length != 4) {
  console.log('Usage: ' + __filename + ' <encryption_key> <message>')
  process.exit(1)
}

console.log(
  decrypt(process.argv[2], process.argv[3])
)
